version: '3.4'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'angaza/summon']
    volumes:
      - ".:/plugin"
