name: Summon
description: Load secrets using Summon from AWS S3, SSM Parameter Store, and elsewhere
author: https://github.com/angaza
requirements:
  - summon
configuration:
  properties:
    provider:
      type: string
    secrets-file:
      type: string
    environment:
      type: string
    yaml:
      type: string
    substitutions:
      type: array
