steps:
  - label: ":hammer: Unit Tests"
    plugins:
      - docker-compose#v2.6.0:
          run: tests
  - label: ":sparkles: Plugin Linter"
    plugins:
      - docker-compose#v2.6.0:
          run: lint
  - label: ":koala: ShellCheck"
    plugins:
      - shellcheck#v1.1.2:
          files: hooks/*
